# Generated by Django 6.0.5 on 2026-06-02 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('prayer', 'Petición'), ('message', 'Mensaje'), ('verse', 'Versículo'), ('gratitude', 'Gratitud'), ('special_moment', 'Momento especial')], default='prayer', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('privacy', models.CharField(choices=[('shared', 'Compartida'), ('private', 'Solo yo')], default='shared', max_length=10)),
                ('state', models.CharField(choices=[('active', 'Activa'), ('answered', 'Respondida'), ('archived', 'Archivada')], default='active', max_length=10)),
                ('pray_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to=settings.AUTH_USER_MODEL)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='gardens.garden')),
            ],
            options={
                'db_table': 'seeds_seed',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_events', to=settings.AUTH_USER_MODEL)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='seeds.seed')),
            ],
            options={
                'db_table': 'seeds_seedevent',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeedInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('prayed', 'Oré')], default='prayed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='seeds.seed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seeds_seedinteraction',
                'unique_together': {('seed', 'user', 'type')},
            },
        ),
    ]
