# Generated by Django 6.0.5 on 2026-06-19 11:30

from django.db import migrations, models


def backfill_growth_points(apps, schema_editor):
    Seed = apps.get_model('seeds', 'Seed')
    for seed in Seed.objects.all():
        seed.growth_points = seed.pray_count
        seed.save(update_fields=['growth_points'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seedinteraction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seed',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seed',
            name='growth_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seed',
            name='last_pray_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_growth_points, noop),
    ]
