# Generated by Django 6.0.5 on 2026-05-30 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('couple', 'Pareja'), ('family', 'Familia'), ('friends', 'Amigos'), ('prayer_group', 'Grupo de oración')], default='personal', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image_url', models.URLField(blank=True)),
                ('privacy', models.CharField(choices=[('private', 'Privado'), ('invite_only', 'Solo invitados')], default='invite_only', max_length=20)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_gardens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gardens_garden',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('used', 'Usada'), ('expired', 'Vencida')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='gardens.garden')),
            ],
            options={
                'db_table': 'gardens_invitation',
            },
        ),
        migrations.CreateModel(
            name='GardenMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('member', 'Miembro')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gardens.garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gardens_gardenmembership',
                'unique_together': {('garden', 'user')},
            },
        ),
    ]
